/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admin;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;
import config.dbConnect;
/**
 *
 * @author ahlde
 */
public class adminDash extends javax.swing.JFrame {
        dbConnect db = new dbConnect();

    /**
     * Creates new form adminDash
     */
    public adminDash() {
        initComponents();
        loadUsers(); // Call the method to populate the table

    }
    
    private void loadUsers() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("User ID");
        model.addColumn("First Name");
        model.addColumn("Last Name");
        model.addColumn("Contact Number");
        model.addColumn("Email");
        model.addColumn("Username");
        model.addColumn("Role");
        model.addColumn("Status");  

        try {
            Connection conn = db.getConnection(); // Get database connection
            if (conn == null) {
                System.out.println("Database connection failed!");
                return;
            }

            String query = "SELECT u_id, u_fname, u_lname, u_contact_number, u_email, u_username, u_role, u_status FROM user";
            Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery(query);

            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getInt("u_id"),
                    rs.getString("u_fname"),
                    rs.getString("u_lname"),
                    rs.getString("u_contact_number"),
                    rs.getString("u_email"),
                    rs.getString("u_username"),
                    rs.getString("u_role"),
                    rs.getString("u_status")
                });
            }

            users_table.setModel(model);
            model.fireTableDataChanged(); // Ensure the table refreshes

            rs.close();
            stmt.close();
            conn.close(); // Close the connection to avoid leaks

        } catch (SQLException ex) {
            System.out.println("Error loading users: " + ex.getMessage());
            ex.printStackTrace();
        }
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        kilidpanel = new javax.swing.JPanel();
        profilepanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        home = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        help = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        request = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        logout = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        usermanage = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        reports = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        Settings = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        babaw = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        wc = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        users_table = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kilidpanel.setBackground(new java.awt.Color(153, 153, 255));
        kilidpanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        kilidpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        profilepanel.setBackground(new java.awt.Color(204, 204, 255));
        profilepanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        profilepanel.setForeground(new java.awt.Color(255, 255, 255));
        profilepanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                profilepanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                profilepanelMouseExited(evt);
            }
        });
        profilepanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Profile");
        profilepanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 60, 30));

        kilidpanel.add(profilepanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 240, 30));

        home.setBackground(new java.awt.Color(204, 204, 255));
        home.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        home.setForeground(new java.awt.Color(255, 255, 255));
        home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                homeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                homeMouseExited(evt);
            }
        });
        home.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Home");
        home.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 60, 30));

        kilidpanel.add(home, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 240, 30));

        help.setBackground(new java.awt.Color(204, 204, 255));
        help.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        help.setForeground(new java.awt.Color(255, 255, 255));
        help.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                helpMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                helpMouseExited(evt);
            }
        });
        help.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Help");
        help.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 60, 30));

        kilidpanel.add(help, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 240, 30));

        request.setBackground(new java.awt.Color(204, 204, 255));
        request.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        request.setForeground(new java.awt.Color(255, 255, 255));
        request.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                requestMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                requestMouseExited(evt);
            }
        });
        request.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Request");
        request.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 60, 30));

        kilidpanel.add(request, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 240, 30));

        logout.setBackground(new java.awt.Color(204, 204, 255));
        logout.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        logout.setForeground(new java.awt.Color(255, 255, 255));
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutMouseExited(evt);
            }
        });
        logout.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Logout");
        logout.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 60, 30));

        kilidpanel.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 240, 30));

        usermanage.setBackground(new java.awt.Color(204, 204, 255));
        usermanage.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        usermanage.setForeground(new java.awt.Color(255, 255, 255));
        usermanage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                usermanageMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                usermanageMouseExited(evt);
            }
        });
        usermanage.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("User Management");
        usermanage.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 200, 30));

        kilidpanel.add(usermanage, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 240, 30));

        reports.setBackground(new java.awt.Color(204, 204, 255));
        reports.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        reports.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                reportsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                reportsMouseExited(evt);
            }
        });
        reports.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Reports");
        reports.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 60, 30));

        kilidpanel.add(reports, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 240, 30));

        Settings.setBackground(new java.awt.Color(204, 204, 255));
        Settings.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Settings.setForeground(new java.awt.Color(255, 255, 255));
        Settings.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SettingsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SettingsMouseExited(evt);
            }
        });
        Settings.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Settings");
        Settings.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 60, 30));

        kilidpanel.add(Settings, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 240, 30));

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/ix--user-profile.png"))); // NOI18N
        kilidpanel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 120));

        jPanel3.add(kilidpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 260, 500));

        babaw.setBackground(new java.awt.Color(153, 153, 255));
        babaw.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        babaw.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        babaw.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        babaw.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/image-80x80.jpg"))); // NOI18N
        jLabel9.setMaximumSize(new java.awt.Dimension(70, 70));
        babaw.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 100));

        jPanel3.add(babaw, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 100));

        wc.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        wc.setForeground(new java.awt.Color(51, 51, 51));
        wc.setText("Welcome Back, Admin!");
        jPanel3.add(wc, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 300, 30));

        date.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        date.setText("Date: 2025");
        jPanel3.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, 270, 30));

        users_table.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        users_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(users_table);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, 620, 420));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void profilepanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profilepanelMouseEntered
        // TODO add your handling code here:
        profilepanel.setOpaque(true);
    profilepanel.setBackground(new java.awt.Color(163, 206, 241)); // A3CEF1

    }//GEN-LAST:event_profilepanelMouseEntered

    private void homeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseEntered
    home.setBackground(new java.awt.Color(163, 206, 241));  
    }//GEN-LAST:event_homeMouseEntered

    private void helpMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_helpMouseEntered
    help.setBackground(new java.awt.Color(163, 206, 241));  
    }//GEN-LAST:event_helpMouseEntered

    private void requestMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_requestMouseEntered
    request.setBackground(new java.awt.Color(163, 206, 241));  
    }//GEN-LAST:event_requestMouseEntered

    private void logoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseEntered
    logout.setBackground(new java.awt.Color(163, 206, 241));  
    }//GEN-LAST:event_logoutMouseEntered

    private void usermanageMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usermanageMouseEntered
    usermanage.setBackground(new java.awt.Color(163, 206, 241));  
    }//GEN-LAST:event_usermanageMouseEntered

    private void reportsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportsMouseEntered
    reports.setBackground(new java.awt.Color(163, 206, 241));  
    }//GEN-LAST:event_reportsMouseEntered

    private void SettingsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SettingsMouseEntered
    Settings.setBackground(new java.awt.Color(163, 206, 241));  
    }//GEN-LAST:event_SettingsMouseEntered

    private void homeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseExited
    home.setBackground(new java.awt.Color(96, 150, 186));  
    }//GEN-LAST:event_homeMouseExited

    private void profilepanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profilepanelMouseExited
    profilepanel.setBackground(new java.awt.Color(96, 150, 186)); // Exit color: 6096BA
    }//GEN-LAST:event_profilepanelMouseExited

    private void requestMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_requestMouseExited
    request.setBackground(new java.awt.Color(96, 150, 186));  
    }//GEN-LAST:event_requestMouseExited

    private void reportsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportsMouseExited
    reports.setBackground(new java.awt.Color(96, 150, 186));  
    }//GEN-LAST:event_reportsMouseExited

    private void usermanageMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usermanageMouseExited
    usermanage.setBackground(new java.awt.Color(96, 150, 186));  
    }//GEN-LAST:event_usermanageMouseExited

    private void SettingsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SettingsMouseExited
    Settings.setBackground(new java.awt.Color(96, 150, 186));  
    }//GEN-LAST:event_SettingsMouseExited

    private void helpMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_helpMouseExited
    help.setBackground(new java.awt.Color(96, 150, 186));  
    }//GEN-LAST:event_helpMouseExited

    private void logoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseExited
    logout.setBackground(new java.awt.Color(96, 150, 186));  
    }//GEN-LAST:event_logoutMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminDash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminDash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminDash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminDash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminDash().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Settings;
    private javax.swing.JPanel babaw;
    private javax.swing.JLabel date;
    private javax.swing.JPanel help;
    private javax.swing.JPanel home;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel kilidpanel;
    private javax.swing.JPanel logout;
    private javax.swing.JPanel profilepanel;
    private javax.swing.JPanel reports;
    private javax.swing.JPanel request;
    private javax.swing.JPanel usermanage;
    private javax.swing.JTable users_table;
    private javax.swing.JLabel wc;
    // End of variables declaration//GEN-END:variables
}
