/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package auth;
import config.dbConnect;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import user.userDashboard;
/**
 *
 * @author axcee
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
    }
       
    userDashboard udb = new userDashboard();
    public static boolean loginAcc(String username, String password) {
          Connection connect;
        dbConnect connector = new dbConnect();
        String query = "SELECT * FROM user WHERE u_username = ? AND u_password = ?";
        try (PreparedStatement pstmt = connector.getConnection().prepareStatement(query)) {
            pstmt.setString(1, username);
            pstmt.setString(2, password);
            ResultSet resultSet = pstmt.executeQuery();
            return resultSet.next();
        } catch (SQLException ex) {
            ex.printStackTrace();
            return false;
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg1 = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        login = new javax.swing.JLabel();
        userff = new javax.swing.JTextField();
        pwl = new javax.swing.JLabel();
        usl = new javax.swing.JLabel();
        loginbtn = new javax.swing.JPanel();
        llogin = new javax.swing.JLabel();
        pwf = new javax.swing.JPasswordField();
        register = new javax.swing.JLabel();
        usl2 = new javax.swing.JLabel();
        Bg2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bg1.setBackground(new java.awt.Color(231, 236, 239));
        bg1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Title.setBackground(new java.awt.Color(0, 0, 0));
        Title.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Title.setForeground(new java.awt.Color(0, 0, 0));
        Title.setText("BarLog");
        bg1.add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 130, 40));

        login.setBackground(new java.awt.Color(0, 0, 0));
        login.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        login.setForeground(new java.awt.Color(0, 0, 0));
        login.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        login.setText("Login");
        bg1.add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 450, 60));

        userff.setBackground(new java.awt.Color(255, 255, 255));
        userff.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        bg1.add(userff, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 300, 40));

        pwl.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        pwl.setForeground(new java.awt.Color(0, 0, 0));
        pwl.setText("Password");
        bg1.add(pwl, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, 300, 20));

        usl.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        usl.setForeground(new java.awt.Color(0, 0, 0));
        usl.setText("Username");
        bg1.add(usl, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 300, 20));

        loginbtn.setBackground(new java.awt.Color(39, 76, 119));
        loginbtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        llogin.setBackground(new java.awt.Color(0, 0, 0));
        llogin.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        llogin.setForeground(new java.awt.Color(255, 255, 255));
        llogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        llogin.setText("Login");
        llogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lloginMouseClicked(evt);
            }
        });
        loginbtn.add(llogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 40));

        bg1.add(loginbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 380, 300, 40));

        pwf.setBackground(new java.awt.Color(255, 255, 255));
        pwf.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        bg1.add(pwf, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 300, 40));

        register.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        register.setForeground(new java.awt.Color(39, 76, 119));
        register.setText("Register?");
        register.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registerMouseClicked(evt);
            }
        });
        bg1.add(register, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 450, 60, 20));

        usl2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        usl2.setForeground(new java.awt.Color(0, 0, 0));
        usl2.setText("Don't have an account?");
        bg1.add(usl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 450, 140, 20));

        getContentPane().add(bg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 600));

        Bg2.setBackground(new java.awt.Color(39, 76, 119));
        Bg2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(Bg2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 0, 450, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lloginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lloginMouseClicked
         String username = userff.getText().trim();
        String password = new String(pwf.getPassword()).trim();
        
        if (username.isEmpty() || password.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please fill in both fields.", "Validation Error", JOptionPane.ERROR_MESSAGE);
        } else if (loginAcc(username, password)) {
            JOptionPane.showMessageDialog(this, "Login successful!", "Welcome", JOptionPane.INFORMATION_MESSAGE);
            // Proceed to the next screen here, e.g., new Dashboard().setVisible(true);
            this.dispose();
            udb.setVisible(true);
            
            
        } else {
            JOptionPane.showMessageDialog(this, "Invalid username or password.", "Login Failed", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_lloginMouseClicked

    private void registerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerMouseClicked
        register rgs = new register();

        this.dispose();
        rgs.setVisible(true);
    }//GEN-LAST:event_registerMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Bg2;
    private javax.swing.JLabel Title;
    private javax.swing.JPanel bg1;
    private javax.swing.JLabel llogin;
    private javax.swing.JLabel login;
    private javax.swing.JPanel loginbtn;
    private javax.swing.JPasswordField pwf;
    private javax.swing.JLabel pwl;
    private javax.swing.JLabel register;
    private javax.swing.JTextField userff;
    private javax.swing.JLabel usl;
    private javax.swing.JLabel usl2;
    // End of variables declaration//GEN-END:variables
}
