package auth;
import config.dbConnect;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import user.userDashboard;
import admin.adminDash;
import java.sql.Statement;
/**
 *
 * @author ahlde
 */
public class login extends javax.swing.JFrame {
    dbConnect db = new dbConnect();

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
    }
    
    
    public String getUserName() {
        try {
            Connection conn = db.getConnection(); // Get database connection
            if (conn == null) {
                System.out.println("Database connection failed!");
            } else {
                
            }

            String query = "SELECT u_fname FROM user WHERE u_username = '" + this.userff.getText() + "'";
            Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery(query);

            if(rs.next()) {
                String userName = rs.getString("u_fname");
                return userName;
            }
            rs.close();
            stmt.close();
            conn.close(); // Close the connection to avoid leaks

        } catch (SQLException ex) {
            System.out.println("Error loading users: " + ex.getMessage());
            ex.printStackTrace();
        }
        return null;
    }
    
    public String name() {
        return this.userff.getText();
    }
    
       
//        userDashboard udb = new userDashboard();
        public static String loginAcc(String username, String password) {
            dbConnect connector = new dbConnect();
            String query = "SELECT u_role, u_status FROM user WHERE u_username = ? AND u_password = ?";

            try (PreparedStatement pstmt = connector.getConnection().prepareStatement(query)) {
                pstmt.setString(1, username);
                pstmt.setString(2, password);
                ResultSet resultSet = pstmt.executeQuery();

                if (resultSet.next()) {
                    String status = resultSet.getString("u_status");

                    if (status.equalsIgnoreCase("inactive")) {
                        return "inactive"; // Indicate that the account is inactive
                    }
                    return resultSet.getString("u_role"); // Return the user's role if active
                }
                resultSet.close();
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
            return null; // Return null if login fails
        }


    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg1 = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        login = new javax.swing.JLabel();
        userff = new javax.swing.JTextField();
        pwl = new javax.swing.JLabel();
        usl = new javax.swing.JLabel();
        loginbtn = new javax.swing.JPanel();
        llogin = new javax.swing.JLabel();
        pwf = new javax.swing.JPasswordField();
        register = new javax.swing.JLabel();
        usl2 = new javax.swing.JLabel();
        Bg2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bg1.setBackground(new java.awt.Color(216, 215, 220));
        bg1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Title.setBackground(new java.awt.Color(0, 0, 0));
        Title.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Title.setText("BARLOG");
        bg1.add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 130, 40));

        login.setBackground(new java.awt.Color(0, 0, 0));
        login.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        login.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        login.setText("Login");
        bg1.add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 450, 60));

        userff.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        userff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userffActionPerformed(evt);
            }
        });
        bg1.add(userff, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 300, 40));

        pwl.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        pwl.setText("Password");
        bg1.add(pwl, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, 300, 20));

        usl.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        usl.setText("Username");
        bg1.add(usl, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 300, 20));

        loginbtn.setBackground(new java.awt.Color(39, 76, 119));
        loginbtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        llogin.setBackground(new java.awt.Color(58, 53, 80));
        llogin.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        llogin.setForeground(new java.awt.Color(255, 255, 255));
        llogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        llogin.setText("Login");
        llogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        llogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lloginMouseClicked(evt);
            }
        });
        loginbtn.add(llogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 40));

        bg1.add(loginbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 380, 300, 40));

        pwf.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        bg1.add(pwf, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 300, 40));

        register.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        register.setForeground(new java.awt.Color(39, 76, 119));
        register.setText("Register here?");
        register.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registerMouseClicked(evt);
            }
        });
        bg1.add(register, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 450, 90, 20));

        usl2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        usl2.setText("Don't have an account?");
        bg1.add(usl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 450, 140, 20));

        getContentPane().add(bg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 600));

        Bg2.setBackground(new java.awt.Color(137, 134, 150));
        Bg2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Bg2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(137, 134, 150));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/3798720.PNG"))); // NOI18N
        jLabel2.setText("jLabel2");
        Bg2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 570));

        getContentPane().add(Bg2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 0, 450, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lloginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lloginMouseClicked
        String username = userff.getText().trim();
        String password = new String(pwf.getPassword()).trim();

        if (username.isEmpty() || password.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please fill in both fields.", "Validation Error", JOptionPane.ERROR_MESSAGE);
        } else {
            String role = loginAcc(username, password);

            if ("inactive".equals(role)) {
                JOptionPane.showMessageDialog(this, "Your account is inactive. Please contact support.", "Account Inactive", JOptionPane.WARNING_MESSAGE);
            } else if (role != null) {
                JOptionPane.showMessageDialog(this, "Login successful!", "Welcome", JOptionPane.INFORMATION_MESSAGE);
                this.dispose(); // Close login window

                if (role.equalsIgnoreCase("admin")) {
                    new adminDash().setVisible(true);  // Redirect to Admin Dashboard
                } else {
                    new userDashboard(getUserName()).setVisible(true);   // Redirect to User Dashboard
                }
            } else {
                JOptionPane.showMessageDialog(this, "Invalid username or password.", "Login Failed", JOptionPane.ERROR_MESSAGE);
            }
        }

    }//GEN-LAST:event_lloginMouseClicked

    private void registerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerMouseClicked
        register rgs = new register();

        this.dispose();
        rgs.setVisible(true);
    }//GEN-LAST:event_registerMouseClicked

    private void userffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userffActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userffActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Bg2;
    private javax.swing.JLabel Title;
    private javax.swing.JPanel bg1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel llogin;
    private javax.swing.JLabel login;
    private javax.swing.JPanel loginbtn;
    private javax.swing.JPasswordField pwf;
    private javax.swing.JLabel pwl;
    private javax.swing.JLabel register;
    private javax.swing.JTextField userff;
    private javax.swing.JLabel usl;
    private javax.swing.JLabel usl2;
    // End of variables declaration//GEN-END:variables
}
