/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package auth;

import javax.swing.JOptionPane;

/**
 *
 * @author ahlde
 */
public class register extends javax.swing.JFrame {

    /**
     * Creates new form Register
     */
    public register() {
        initComponents();
        
        
    }
    
    private boolean isValidEmail(String email) {
        String emailRegex = "^[A-Za-z0-9+_.-]+@[A-Za-z0-9.-]+$";
        return email.matches(emailRegex);
    }

    // Helper method to check if username is already taken
    // This would typically involve checking against a database
    private boolean isUsernameTaken(String username) {
        // TODO: Implement actual username check against database or user store
        // For now, return false as a placeholder
        return false;
    }
    private boolean isAllFieldsEmpty() {
        return fname1.getText().trim().isEmpty() &&
               lname.getText().trim().isEmpty() &&
               email.getText().trim().isEmpty() &&
               contactff.getText().trim().isEmpty() &&
               userff.getText().trim().isEmpty() &&
               pwf.getPassword().length == 0 &&
               roleb.getSelectedIndex() == 0;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        bg2 = new javax.swing.JPanel();
        login = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        usl = new javax.swing.JLabel();
        userff = new javax.swing.JTextField();
        pwf = new javax.swing.JPasswordField();
        pwl = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        ffname1 = new javax.swing.JLabel();
        lname1 = new javax.swing.JLabel();
        lname = new javax.swing.JTextField();
        fname1 = new javax.swing.JTextField();
        emaill = new javax.swing.JLabel();
        adff = new javax.swing.JTextField();
        adl = new javax.swing.JLabel();
        contactff = new javax.swing.JTextField();
        contl = new javax.swing.JLabel();
        regisiterbtn = new javax.swing.JPanel();
        register = new javax.swing.JLabel();
        usl1 = new javax.swing.JLabel();
        usl2 = new javax.swing.JLabel();
        rolel = new javax.swing.JLabel();
        roleb = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bg1.setBackground(new java.awt.Color(153, 153, 255));
        bg1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/3798720.PNG"))); // NOI18N
        bg1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, -1, -1));

        getContentPane().add(bg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 600));

        bg2.setBackground(new java.awt.Color(204, 204, 255));
        bg2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        login.setBackground(new java.awt.Color(0, 0, 0));
        login.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        login.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        login.setText("Register");
        bg2.add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 450, 60));

        title.setBackground(new java.awt.Color(0, 0, 0));
        title.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        title.setText("BARLOG");
        bg2.add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 130, 40));

        usl.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        usl.setText("Username");
        bg2.add(usl, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, 300, 20));

        userff.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        bg2.add(userff, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 370, 300, 30));

        pwf.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        bg2.add(pwf, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 420, 300, 30));

        pwl.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        pwl.setText("Password");
        bg2.add(pwl, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 400, 300, 20));

        email.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        bg2.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 300, 30));

        ffname1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        ffname1.setText("First Name");
        bg2.add(ffname1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 140, 20));

        lname1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lname1.setText("Last Name");
        bg2.add(lname1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, 140, 20));

        lname.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lnameActionPerformed(evt);
            }
        });
        bg2.add(lname, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, 140, 30));

        fname1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        bg2.add(fname1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 140, 30));

        emaill.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        emaill.setText("Email");
        bg2.add(emaill, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 120, 20));

        adff.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        bg2.add(adff, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, 300, 30));

        adl.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        adl.setText("Address");
        bg2.add(adl, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 120, 20));

        contactff.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        bg2.add(contactff, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, 300, 30));

        contl.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        contl.setText("Contact #");
        bg2.add(contl, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, 120, 20));

        regisiterbtn.setBackground(new java.awt.Color(255, 255, 255));
        regisiterbtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        register.setBackground(new java.awt.Color(0, 0, 0));
        register.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        register.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        register.setText("Register");
        register.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registerMouseClicked(evt);
            }
        });
        regisiterbtn.add(register, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 40));

        bg2.add(regisiterbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 520, 300, 40));

        usl1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        usl1.setForeground(new java.awt.Color(51, 102, 255));
        usl1.setText("Login here.");
        usl1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usl1MouseClicked(evt);
            }
        });
        bg2.add(usl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 570, 90, 20));

        usl2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        usl2.setText("Already have an account?");
        bg2.add(usl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 570, 140, 20));

        rolel.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        rolel.setText("Role");
        bg2.add(rolel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 450, 300, 20));

        roleb.setForeground(new java.awt.Color(255, 255, 255));
        roleb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Role", "Citizen", "Officials" }));
        bg2.add(roleb, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 470, 300, 30));

        getContentPane().add(bg2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 0, 450, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void registerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerMouseClicked
        boolean isValid = true;

        if (isAllFieldsEmpty()) {
            JOptionPane.showMessageDialog(this, "Please fill out the registration form", "Empty Form", JOptionPane.ERROR_MESSAGE);
            return;
        }
   
        if (fname1.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "First Name cannot be empty", "Validation Error", JOptionPane.ERROR_MESSAGE);
            isValid = false;
        }

        // Validate Last Name
        if (lname.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Last Name cannot be empty", "Validation Error", JOptionPane.ERROR_MESSAGE);
            isValid = false;
        }

        // Validate Email
        String emailText = email.getText().trim();
        if (emailText.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Email cannot be empty", "Validation Error", JOptionPane.ERROR_MESSAGE);
            isValid = false;
        } else if (!isValidEmail(emailText)) {
            JOptionPane.showMessageDialog(this, "Invalid email format", "Validation Error", JOptionPane.ERROR_MESSAGE);
            isValid = false;
        }

        // Validate Contact Number
        String contactText = contactff.getText().trim();
        if (contactText.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Contact Number cannot be empty", "Validation Error", JOptionPane.ERROR_MESSAGE);
            isValid = false;
        } else if (!contactText.matches("\\d+")) {
            JOptionPane.showMessageDialog(this, "Contact Number must contain only numbers", "Validation Error", JOptionPane.ERROR_MESSAGE);
            isValid = false;
        }

        // Validate Username
        String usernameText = userff.getText().trim();
        if (usernameText.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Username cannot be empty", "Validation Error", JOptionPane.ERROR_MESSAGE);
            isValid = false;
        } else if (isUsernameTaken(usernameText)) {
            JOptionPane.showMessageDialog(this, "Username is already taken", "Validation Error", JOptionPane.ERROR_MESSAGE);
            isValid = false;
        }

        // Validate Password
        String passwordText = new String(pwf.getPassword());
        if (passwordText.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Password cannot be empty", "Validation Error", JOptionPane.ERROR_MESSAGE);
            isValid = false;
        } else if (passwordText.length() < 8) {
            JOptionPane.showMessageDialog(this, "Password must be at least 8 characters long", "Validation Error", JOptionPane.ERROR_MESSAGE);
            isValid = false;
        }

        // Validate Role
        if (roleb.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "Please select a role", "Validation Error", JOptionPane.ERROR_MESSAGE);
            isValid = false;
        }

        // If all validations pass, proceed with registration
        if (isValid) {
            // TODO: Implement actual registration logic
            JOptionPane.showMessageDialog(this, "Registration Successful!", "Success", JOptionPane.INFORMATION_MESSAGE);
             
        }
    }//GEN-LAST:event_registerMouseClicked

    private void lnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lnameActionPerformed

    private void usl1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usl1MouseClicked
       login lg = new login();
       
        this.dispose();
        lg.setVisible(true);
    }//GEN-LAST:event_usl1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField adff;
    private javax.swing.JLabel adl;
    private javax.swing.JPanel bg1;
    private javax.swing.JPanel bg2;
    private javax.swing.JTextField contactff;
    private javax.swing.JLabel contl;
    private javax.swing.JTextField email;
    private javax.swing.JLabel emaill;
    private javax.swing.JLabel ffname1;
    private javax.swing.JTextField fname1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField lname;
    private javax.swing.JLabel lname1;
    private javax.swing.JLabel login;
    private javax.swing.JPasswordField pwf;
    private javax.swing.JLabel pwl;
    private javax.swing.JPanel regisiterbtn;
    private javax.swing.JLabel register;
    private javax.swing.JComboBox<String> roleb;
    private javax.swing.JLabel rolel;
    private javax.swing.JLabel title;
    private javax.swing.JTextField userff;
    private javax.swing.JLabel usl;
    private javax.swing.JLabel usl1;
    private javax.swing.JLabel usl2;
    // End of variables declaration//GEN-END:variables
}
